import { useStoredRef } from '../store/index.js'
import { createNextWeeklyTask } from '../taskRecurrence.js'
import { classifyTask } from '../smartClassify.js'
import { detectCategory } from '../ledger.js'

function stamp() { return new Date().toISOString() }
function createId(prefix) { return `${prefix}${Date.now()}${Math.random().toString(36).slice(2, 6)}` }
function origin(value = {}) { return { createdFrom: value.createdFrom || 'manual', sourceType: value.sourceType || '', sourceId: value.sourceId || '', relationId: value.relationId || '' } }
function dateString(value) { const d = new Date(value); const p = (n) => String(n).padStart(2, '0'); return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}` }
function addMonths(base, count) { const day = base.getDate(); const next = new Date(base.getFullYear(), base.getMonth() + count, 1); next.setDate(Math.min(day, new Date(next.getFullYear(), next.getMonth() + 1, 0).getDate())); return next }
function nextBillDate(bill) { const current = new Date(`${bill.nextDate}T00:00:00`); let next = bill.cycle === 'weekly' ? new Date(current.getTime() + 7 * 86400000) : bill.cycle === 'quarterly' ? addMonths(current, 3) : bill.cycle === 'yearly' ? addMonths(current, 12) : bill.cycle === 'once' ? current : addMonths(current, 1); const today = new Date(); today.setHours(0, 0, 0, 0); while (next <= today && bill.cycle !== 'once') next = bill.cycle === 'weekly' ? new Date(next.getTime() + 7 * 86400000) : bill.cycle === 'quarterly' ? addMonths(next, 3) : bill.cycle === 'yearly' ? addMonths(next, 12) : addMonths(next, 1); return dateString(next) }

export function useDomainCommands() {
  const tasks = useStoredRef('sl_tasks', []); const courses = useStoredRef('sl_courses', []); const milestones = useStoredRef('sl_exams', []); const bills = useStoredRef('sl_bills', []); const transactions = useStoredRef('sl_expenses', []); const events = useStoredRef('sl_events', []); const notes = useStoredRef('sl_quick_notes', [])
  function createTask(value) { const now = stamp(); const task = classifyTask({ id: value.id || createId('t'), title: String(value.title || '').trim(), done: false, status: 'pending', createdAt: now, updatedAt: now, course: value.course || '', courseId: value.courseId || '', dueDate: value.dueDate || '', dueTime: value.dueTime || '', priority: value.priority || 'normal', note: value.note || '', sourceText: value.sourceText || '', estimateMinutes: Number(value.estimateMinutes) || 0, repeat: value.repeat || 'none', kind: value.kind || 'todo', ...origin(value) }, courses.value); if (!task.title) throw new Error('请填写待办内容'); tasks.value.push(task); return task }
  function updateTask(id, value) { const item = tasks.value.find((task) => task.id === id); if (!item) return null; Object.assign(item, value, { updatedAt: stamp() }); return item }
  function toggleTask(id) { const item = tasks.value.find((task) => task.id === id); if (!item) return null; const now = stamp(); item.done = !item.done; item.status = item.done ? 'completed' : 'pending'; item.completedAt = item.done ? now : null; item.updatedAt = now; if (item.done && item.repeat === 'weekly' && item.dueDate && !item.repeatGeneratedAt) { item.repeatGeneratedAt = now; const next = createNextWeeklyTask(item); if (next) tasks.value.push({ ...next, status: 'pending', updatedAt: now, createdFrom: item.createdFrom || 'manual', sourceType: 'task-repeat', sourceId: item.id }) } return item }
  function createMilestone(value) { const now = stamp(); const item = { id: value.id || createId('e'), name: String(value.name || value.title || '').trim(), date: value.date || '', time: value.time || '', location: value.location || '', category: value.category || '学习', repeat: value.repeat || 'none', pinned: Boolean(value.pinned), courseId: value.courseId || '', courseName: value.courseName || value.course || '', reviewProgress: Number(value.reviewProgress) || 0, kind: value.kind || 'countdown', createdAt: now, updatedAt: now, ...origin(value) }; if (!item.name || !item.date) throw new Error('请补充名称和目标日期'); milestones.value.push(item); return item }
  function updateMilestone(id, value) { const item = milestones.value.find((entry) => entry.id === id); if (!item) return null; Object.assign(item, value, { updatedAt: stamp() }); return item }
  function createEvent(value) { const now = stamp(); const item = { id: value.id || createId('event'), title: String(value.title || '').trim(), date: value.date || '', time: value.time || '', courseId: value.courseId || '', courseName: value.courseName || value.course || '', note: value.note || '', createdAt: now, updatedAt: now, ...origin(value) }; if (!item.title) throw new Error('请填写日程内容'); events.value.push(item); return item }
  function createNote(value) { const now = stamp(); const content = String(value.content || value.note || value.title || '').trim(); const firstLine = content.split(/\r?\n/).map((line) => line.trim()).find(Boolean) || ''; const autoTitle = firstLine || content.replace(/\s+/g, ' '); const title = String(value.title || '').trim() || autoTitle.slice(0, 42); const item = { id: value.id || createId('note'), title: title.slice(0, 42), content, courseId: value.courseId || '', courseName: value.courseName || value.course || '', sourceText: value.sourceText || value.raw || content, tags: Array.isArray(value.tags) ? value.tags : [], createdAt: now, updatedAt: now, ...origin(value) }; if (!item.content) throw new Error('请填写笔记内容'); notes.value.unshift(item); return item }
  function updateNote(id, value) { const item = notes.value.find((note) => note.id === id); if (!item) return null; Object.assign(item, value, { updatedAt: stamp() }); return item }
  function createTransaction(value) { const now = stamp(); const item = { id: value.id || createId('ex'), name: String(value.name || value.title || '').trim(), amount: Number(value.amount), cat: value.cat || value.category || detectCategory(value.name || value.title), date: value.date || now.slice(0, 10), time: value.time || now.slice(11, 16), note: value.note || '', account: value.account || '', direction: value.direction === 'income' || value.type === 'income' ? 'income' : 'expense', source: value.source || value.createdFrom || 'manual', billId: value.billId || '', billingPeriodKey: value.billingPeriodKey || '', createdAt: now, updatedAt: now, ...origin(value) }; if (!item.name || !(item.amount > 0)) throw new Error('请补充正确金额和用途'); transactions.value.push(item); return item }
  function updateTransaction(id, value) { const item = transactions.value.find((entry) => entry.id === id); if (!item) return null; Object.assign(item, value, { updatedAt: stamp() }); return item }
  function createBill(value) { const now = stamp(); const item = { id: value.id || createId('bill'), name: String(value.name || value.title || '').trim(), amount: Number(value.amount), cycle: value.cycle || 'monthly', nextDate: value.nextDate || value.date || '', remindDays: Number(value.remindDays ?? 3), autoRenew: value.autoRenew !== false, active: value.active !== false, note: value.note || '', account: value.account || '', createdAt: now, updatedAt: now, ...origin(value) }; if (!item.name || !(item.amount > 0) || !item.nextDate) throw new Error('请补充账单名称、金额和日期'); bills.value.push(item); return item }
  function updateBill(id, value) { const item = bills.value.find((entry) => entry.id === id); if (!item) return null; Object.assign(item, value, { updatedAt: stamp() }); return item }
  function payBill(id) { const bill = bills.value.find((item) => item.id === id); if (!bill) return null; const period = bill.nextDate; const duplicate = transactions.value.find((item) => item.billId === bill.id && item.billingPeriodKey === period); if (duplicate) return { bill, transaction: duplicate, duplicate: true }; const transaction = createTransaction({ name: bill.name, amount: bill.amount, category: bill.category, date: dateString(new Date()), note: '来自固定账单', account: bill.account, billId: bill.id, billingPeriodKey: period, source: 'bill', createdFrom: 'bill', sourceType: 'bill', sourceId: bill.id }); bill.nextDate = nextBillDate(bill); bill.updatedAt = stamp(); return { bill, transaction, duplicate: false } }
  return { tasks, courses, milestones, bills, transactions, events, notes, createTask, updateTask, toggleTask, createMilestone, updateMilestone, createEvent, createNote, updateNote, createTransaction, updateTransaction, createBill, updateBill, payBill }
}
